### ISSUE TITLE
Executing command `jx gitops scheduler` failed to update config_updater in plugin.yaml.

### ISSUE THREAD

**Issue by shichanson** [jenkins-x-plugins/jx-gitops#834]

**Comment by shichanson** [comment]
my in-repo.yaml
```yaml
apiVersion: gitops.jenkins-x.io/v1alpha1
kind: Scheduler
metadata:
  name: in-repo
spec:
  approve:
    issue_required: false
    lgtm_acts_as_approve: true
    require_self_approval: true
  config_updater:
    config_file: lighthouse/config.yaml
    plugin_file: lighthouse/plugins.yaml
    map:
      lighthouse/scripts/*:
        name: ci-scripts
      lighthouse/config/kube-config/*:
        name: kube-config
        additional_namespaces:
          - kube-deploy
  merger:
    blocker_label: ""
    max_goroutines: 0
    merge_method: squash
    policy:
      from-branch-protection: true
      optional-contexts: { }
      required-contexts: { }
      required-if-present-contexts: { }
      skip-unknown-contexts: false
    pr_status_base_url: ""
    squash_label: ""
    target_url: http://lighthouse{{ .Requirements.ingress.namespaceSubDomain }}{{ .Requirements.ingress.domain }}/merge/status
  # lets look in the source repository for trigger files
  in_repo: true
  plugins:
    entries:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
  external_plugins:
    Replace: true
    entries:
    - name: cd-indicators
      endpoint: "http://cd-indicators.jx.svc.cluster.local/lighthouse/events"
    - name: lighthouse-webui-plugin
      endpoint: "http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events"
  queries:
    - excludedBranches: { }
      included_branches: { }
      labels:
        entries:
          - approved
      milestone: ""
      missingLabels:
        entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
      review_approved_required: false
    - excludedBranches: { }
      included_branches: { }
      labels:
        entries:
          - updatebot
      milestone: ""
      missingLabels:
        entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
      review_approved_required: false
  policy:
    protect_tested: true
  schedulerAgent:
    agent: tekton
  trigger:
    ignore_ok_to_test: false
    join_org_url: ""
    only_org_members: false
    trusted_org: todo
  welcome:
    - message_template: Welcome
```

**Comment by shichanson** [comment]
```
apiVersion: v1
data:
  plugins.yaml: |
    approve:
    - lgtm_acts_as_approve: true
      repos:
      - devops/golang-jx3-demo
      require_self_approval: true
    cat: {}
    cherry_pick_unapproved: {}
    config_updater:
      gzip: false
      maps:
        env/prow/job.yaml:
          name: config
        env/prow/plugins.yaml:
          name: plugins
.........
```
No matter how I modify the config_updater field in in-repo.yaml, plugins.yaml. still does not change anything. Don't know how should I solve this problem。 
jx gitops version: 0.6.3
