### ISSUE TITLE
Adding new charts for private DNS

### ISSUE THREAD

**Issue by chrislovecnm** [jenkins-x-plugins/jx-gitops#846]
Hi all

I need to get a second external dns controller and nginx ingress working for internal DNS for webhooks and other components.  I need both internal and external ingress for the webhooks and other components because of the VPN connection we use into AWS.  The problem is that `jx gitops update` is adding a new line in the values array for a `values.yaml.gotmpl` file, and that file is 
overwriting some of the values I am setting.

I have added a new directory:

```
helmfiles/external-dns-private
```

In that directory I have added
helmfile.yaml
```yaml
filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: external-dns-private
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: stable
  url: https://charts.helm.sh/stable
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
releases:
- chart: bitnami/external-dns
  version: 6.0.2
  condition: jxRequirementsIngressExternalDNS.enabled
  name: external-dns-private
  values:
  - values.yaml.gotmpl
  - jx-values.yaml
  - ../../versionStream/charts/bitnami/external-dns/values.yaml.gotmpl
- chart: ingress-nginx/ingress-nginx
  version: 3.12.0
  name: nginx-ingress-private
  values:
  - nginx-values.yaml.gotmpl
  - jx-values.yaml
  - ../../versionStream/charts/ingress-nginx/ingress-nginx/values.yaml.gotmpl
templates: {}
renderedvalues: {}
```

When I run `jx gitops update` I am getting  the following line added to the values section.
This is causing some of my values to be overwritten. What options do I have?

```
 values:
 - ../../versionStream/charts/bitnami/external-dns/values.yaml.gotmpl
```

**Comment by andynelson** [comment]
when we've had similar issues, we figure that If you move the auto-added line to be the first, rather than the last one in the list then your values will override the ones from versionStream
e.g.
```
- chart: bitnami/external-dns
  version: 6.0.2
  condition: jxRequirementsIngressExternalDNS.enabled
  name: external-dns-private
  values:
  - ../../versionStream/charts/bitnami/external-dns/values.yaml.gotmpl
  - values.yaml.gotmpl
  - jx-values.yaml
```

does that help?
